# If you have OpenSSL installed, we recommend updating
# the following line to use "https"
source 'http://rubygems.org'

gem "middleman", "~>3.0.13"
gem "middleman-sprockets"
gem "middleman-syntax", '1.1.1'
gem "redcarpet"

gem "slim"
gem "skim"
gem "sass"
gem "code_sync", path: File.join("..")