# If you have OpenSSL installed, we recommend updating
# the following line to use "https"
source 'https://rubygems.org'

gem "haml"
gem "sass"
gem "coffee-script"
gem "middleman-sprockets"
gem "pry"
gem "code_sync", path: "/Users/jonathan/Projects/code_sync"

gem "middleman", "~>3.0.12"